#!/usr/bin/env bash
# This script is displaying a Bash script that displays the content of the file /etc/passwd.

FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
	do
		echo "$username, $userid, $comment $homedir"
	done < $FILENAME
