#!/usr/bin/env bash
# This script is displaying a Bash script that displays the content of the file /etc/passwd.

while IFS= read -r lines
do
	echo '\'"$lines'\'" | cut -d: -f1,3,6;
done < /etc/passwd"
