#!/usr/bin/env bash
# This script is displaying a Bash script that displays the content of the file /etc/passwd.

FILENAME="/etc/passwd"
while IFS=: read -r username userid homedir
	do
		echo "$username"
		echo "$userid"
		echo "$homedir"
	done < $FILENAME
