#!/usr/bin/env bash
# This script is displaying a Bash script that displays: 1. The content of the current directory. 2. In a list format. 3. Where only the part of the name after the first dash is displayed

list-$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
